package com.PostTracking.PostTracking;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class AddPackageTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
	//System.out.println(System.getProperty("user.dir")+"\\Support\\chromedriver.exe");
	System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+"\\Support\\chromedriver.exe");
	driver = new ChromeDriver();
	js = (JavascriptExecutor) driver;
	vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void addPackage() {
 driver.get("http://127.0.0.1:8080/");
 driver.manage().window().setSize(new Dimension(1296, 1000));
 driver.findElement(By.linkText("Packages")).click();
 driver.findElement(By.linkText("Add Package")).click();
 driver.findElement(By.id("selcustomer")).click();
 {
   WebElement dropdown = driver.findElement(By.id("selcustomer"));
   dropdown.findElement(By.xpath("//option[. = 'Sansa Stark']")).click();
 }
 driver.findElement(By.id("selcustomer")).click();
 driver.findElement(By.id("txtWeight")).click();
 driver.findElement(By.id("txtWeight")).click();
 {
   WebElement element = driver.findElement(By.id("txtWeight"));
   Actions builder = new Actions(driver);
   builder.doubleClick(element).perform();
 }
 driver.findElement(By.id("txtWeight")).click();
 driver.findElement(By.id("txtWeight")).sendKeys("15");
 driver.findElement(By.id("txtVolume")).sendKeys("20");
 driver.findElement(By.id("txtRecipient")).sendKeys("Sersei");
 driver.findElement(By.id("txtAddress")).sendKeys("The Castle Road");
 driver.findElement(By.id("txtCity")).sendKeys("Somewhere");

 driver.findElement(By.id("selOrigin")).click();

 {
   WebElement dropdown = driver.findElement(By.id("selOrigin"));
   dropdown.findElement(By.xpath("//option[. = 'Winterfell']")).click();
 }
 
 driver.findElement(By.id("txtProvince")).sendKeys("Some Place");
 driver.findElement(By.id("txtZipCode")).sendKeys("ZDZ VCX");
 
 driver.findElement(By.id("btnSeekPath")).click();
 try {
		Thread.sleep(10000);
	} catch (InterruptedException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
 
 driver.findElement(By.cssSelector("#paths .card-body .btn")).click();
}
}

