package com.PostTracking.PostTracking;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class AddRouteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+"\\Support\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addRouteTest() {
    driver.get("http://127.0.0.1:8080/");
    driver.manage().window().setSize(new Dimension(1920, 973));
    driver.findElement(By.linkText("Routes")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.id("DropDownTrigger")).click();
    driver.findElement(By.linkText("Dodge Ram 3500")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .form-group")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("td:nth-child(2) > .form-group"));
      dropdown.findElement(By.xpath("//option[. = 'Castle Black']")).click();
    }
    driver.findElement(By.cssSelector("td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > input")).sendKeys("2019-07-01T01:01");
    driver.findElement(By.cssSelector("td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > input")).sendKeys("2019-07-02T01:01");
    driver.findElement(By.id("CreateRow")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .form-group")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .form-group"));
      dropdown.findElement(By.xpath("//option[. = 'Castle Black']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > .form-group")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > input")).sendKeys("2019-07-03T01:01");
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4) > input")).sendKeys("2019-07-04T01:01");
    driver.findElement(By.id("CreateRoute")).click();
    driver.findElement(By.id("modalForm")).click();
    driver.findElement(By.cssSelector("body")).click();
  }
}
