package com.PostTracking.Tests;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.interactions.InputSource;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.Sleeper;
import org.openqa.selenium.JavascriptExecutor;

import static org.junit.Assert.assertEquals;

import java.util.*;
public class AddRouteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+"\\Support\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addRouteTest() {
	  try {
		    driver.get("http://127.0.0.1:8080/");
		    driver.manage().window().setSize(new Dimension(1296, 1000));
		    driver.findElement(By.linkText("Routes")).click();
		    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
		    {
		      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(1)"));
		      Actions builder = new Actions(driver);
		      builder.moveToElement(element).perform();
		    }
		    {
		      WebElement element = driver.findElement(By.tagName("body"));
		      Actions builder = new Actions(driver);
		      builder.moveToElement(element, 0, 0).perform();
		    }
		    driver.findElement(By.id("DropDownTrigger")).click();
		    driver.findElement(By.linkText("DragaoBaoBao")).click();
		    driver.findElement(By.cssSelector("td:nth-child(2) > .form-group")).click();
		    {
		      WebElement dropdownElement = driver.findElement(By.cssSelector("td:nth-child(1) > .form-group"));
		      Select dropdown = new Select(dropdownElement);
		      dropdown.selectByIndex(8);
		      WebElement dropdownElement2 = driver.findElement(By.cssSelector("td:nth-child(2) > .form-group"));
		      Select dropdown2 = new Select(dropdownElement2);
		      dropdown2.selectByIndex(14);
		    }
		    driver.findElement(By.cssSelector("td:nth-child(3) > input")).sendKeys("01/01/002019 01:01PM");
		    driver.findElement(By.cssSelector("td:nth-child(4) > input")).sendKeys("01/02/002019 01:01PM");
		    
		    //CREATE ANOTHER ROW
		    driver.findElement(By.id("CreateRow")).click();
		    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .form-group")).click();
		    {
		      WebElement dropdownElement = driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .form-group"));
		      Select dropdown = new Select(dropdownElement);
		      dropdown.selectByIndex(14);
		      WebElement dropdownElement2 = driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > .form-group"));
		      Select dropdown2 = new Select(dropdownElement2);
		      dropdown2.selectByIndex(8);
		    }
		    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > input")).sendKeys("01/03/002019 01:01PM");
		    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4) > input")).sendKeys("01/04/002019 01:01PM");
		    driver.findElement(By.id("CreateRoute")).click();
		    
		    Thread.sleep(1000);
		    
		    String result = driver.findElement(By.id("ErrorMessage")).getText();
		    assertEquals(result, "Routes created successfully");
	} catch (Exception e) {
		// TODO: handle exception
		System.out.println(e.getMessage());
	}
  }
}
